<style type="text/css">

body#mainbody {
    background-color: #041325; /* override the page background color here */
}

pre, .code {
    margin: 5px 0; /* override the default margin for pre, .code elements here */
    padding: 5px;  /* override the default padding for pre, .code elements here */
}

span {
   float: left;
   width: 120px;
 align: center;
}
span.unknown {
    background-color: white;
    text-align: center;
}
span.bad {
    background-color: LightSalmon;
    text-align: center;
}
span.good {
    background-color: LightGreen;
    text-align: center;
}
input.filter {
    width: 80% !important;
}

</style>
