<?php

  // only for the download of packaged zip files we need this
  if (!extension_loaded('zip')) {
    dl('zip.so');
  }

  # get the variables from the parent page, or use pre-defined values
  if (!isset($_POST['_v']))
    $version       = "";
  else
    $version       = $_POST['_v'];
  if (!isset($_POST['cookie']))
    $cookie       = 42;
  else
    $cookie       = $_POST['cookie'];
  if (!isset($_POST['user_name']))
    $user_name  = "hauke";
  else
    $user_name    = $_POST['user_name'];
  if (!isset($_POST['project_name']))
    $project_name = 'PING';
  else
    $project_name = $_POST['project_name'];
  if (!isset($_POST['returnFile']))
    $returnFile = 'false';
  else
    $returnFile = $_POST['returnFile'];
  if (!isset($_POST['vertexwise']))
    $vertexwise = 0;
  else
    $vertexwise = $_POST['vertexwise'];
  if (!isset($_POST['request']))
    $request = -1;
  else
    $request = $_POST['request'];

  if (!isset($_POST['expert'])) {
    $expert = <<<EOT
#
# Expert mode text generated by the web-site interface
#

dependent.measure="CortArea.Total"
covariates.usr=""
covariates.sys="africa+amerind+eastAsia+oceania+centralAsia+DeviceSerialNumber"
independent.variable="s(Age)"
smoothing.interaction="Sex"

EOT;
  } else
    $expert       = rawurldecode($_POST['expert']);

  // The R code itself
  // Important: php variables are used as is, for example $expert
  //            is replaced with its text representation by php. 
  //            R variables can have the "$"-sign as well, in that case
  //            one needs to quote it with "\$" in the text.
  //
  // Input directory structure:
  //   /opt/dataportal/data/PING/data_uncorrected/PING_MRI_DTI_Complete_QCed.csv
  //   /opt/dataportal/data/PING/data_uncorrected/PING_Behavior.csv  <- super spreadsheet
  //   /opt/dataportal/code/StatisticsGAM2/user_code/userdata_PING_hauke.csv  <- user defined spreadsheet
  // Output directory structure (sub-directories for the project/user/cookie are created therein)
  //   /opt/dataportal/code/StatisticsGAM2/
  //
  // Requirements for output:
  //  R stdout should contain all information displayed in the "Statistics Summary" section of the webpage. 
  //
  //  /opt/dataportal/code/StatisticsGAM2/curves/hauke_PING_curves/CortThick.Mean42.csv:
  //     "s(Age)", "AA", "GA", "GG"
  //     3.04,"3.2","4.3","3.2"
  //     ...
  //  [^ column header contains names of the levels and sample points for independent variable in first column]
  //
  //  /opt/dataportal/code/StatisticsGAM2/curves/hauke_PING_curves/hauke_PING_Corrected42.tsv:
  //     "SubjID","Site","VisitID","VisitNumber","StudyDate","Sex","Age","Group","Manufacturer","ManufacturersModelName","DeviceSerialNumber","Age","CortThick.Mean","GroupingByIndex"
  //     ...
  //  [^ Needs to contain the dependent and independent variable (without "s(<>)"). "GroupingByIndex" is a column of levels for each row. ]

  $RCode = <<<EOT

$expert

EOT;

if (strcmp($returnFile, 'true') == 0) {
   // return a filename on the server of zip file with data (in R) and rcode
   $file="rcode_include.txt";
   $file2="StatsScript_GAM.R";
   $destination="curves/package.zip";
   if (file_exists($destination))
     unlink($destination);
   $cachedData="user_code/usercache_".$project_name."_".$user_name.$version.".RData";
   file_put_contents($file,$RCode);
   $zip = new ZipArchive();
   if ($zip->open($destination, ZIPARCHIVE::OVERWRITE) !== true) {
      echo "Error: could not create a zip file at" . $destination;
      syslog(LOG_INFO, "error: could not create zip file at " . $destination);
      return false;
   }
   //add the files
   $zip->addFile($file ,"rcode_include.txt");
   $zip->addFile($file2,"StatsScript_GAM.R");
   if (file_exists($cachedData))
     $zip->addFile($cachedData,"usercache.RData");

   // now add vertex data as well
   $file3="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-icoarea-lh.csv";
   $file4="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-icoarea-lh.dat";
   $file5="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-icoarea-rh.csv";
   $file6="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-icoarea-rh.dat";
   $file7="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-thick-rh.csv";
   $file8="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-thick-rh.dat";
   $file9="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-thick-lh.csv";
   $file10="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-thick-lh.dat";
   $file11="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-volume-rh.csv";
   $file12="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-volume-rh.dat";
   $file13="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-volume-lh.csv";
   $file14="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-volume-lh.dat";
   $file15="../../applications/SurfaceViewer/data/ico5_lh_surfmask.json";
   $file16="../../applications/SurfaceViewer/data/ico5_rh_surfmask.json";
   $file17="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-geometry-lh.csv";
   $file18="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-geometry-lh.dat";
   $file19="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-geometry-rh.csv";
   $file20="../../data/".$project_name."/data_uncorrected".$version."/VertexStatsInput/".$project_name."_concat_surfstats_sm2819-geometry-rh.dat";

   if (is_readable($file3)) $zip->addFile($file3, $project_name."_concat_surfstats_sm2819-icoarea-lh.csv");
   if (is_readable($file4)) $zip->addFile($file4, $project_name."_concat_surfstats_sm2819-icoarea-lh.dat");
   if (is_readable($file5)) $zip->addFile($file5, $project_name."_concat_surfstats_sm2819-icoarea-rh.csv");
   if (is_readable($file6)) $zip->addFile($file6, $project_name."_concat_surfstats_sm2819-icoarea-rh.dat");

   if (is_readable($file7)) $zip->addFile($file7, $project_name."_concat_surfstats_sm2819-thick-lh.csv");
   if (is_readable($file8)) $zip->addFile($file8, $project_name."_concat_surfstats_sm2819-thick-lh.dat");
   if (is_readable($file9)) $zip->addFile($file9, $project_name."_concat_surfstats_sm2819-thick-rh.csv");
   if (is_readable($file10)) $zip->addFile($file10, $project_name."_concat_surfstats_sm2819-thick-rh.dat");

   if (is_readable($file11)) $zip->addFile($file11, $project_name."_concat_surfstats_sm2819-volume-lh.csv");
   if (is_readable($file12)) $zip->addFile($file12, $project_name."_concat_surfstats_sm2819-volume-lh.dat");
   if (is_readable($file13)) $zip->addFile($file13, $project_name."_concat_surfstats_sm2819-volume-rh.csv");
   if (is_readable($file14)) $zip->addFile($file14, $project_name."_concat_surfstats_sm2819-volume-rh.dat");

   if (is_readable($file15)) $zip->addFile($file15, "ico5_lh_surfmask.json");
   if (is_readable($file16)) $zip->addFile($file16, "ico5_rh_surfmask.json");

   if (is_readable($file17)) $zip->addFile($file17, $project_name."_concat_surfstats_sm2819-geometry-lh.csv");
   if (is_readable($file18)) $zip->addFile($file18, $project_name."_concat_surfstats_sm2819-geometry-lh.dat");
   if (is_readable($file19)) $zip->addFile($file19, $project_name."_concat_surfstats_sm2819-geometry-rh.csv");
   if (is_readable($file20)) $zip->addFile($file20, $project_name."_concat_surfstats_sm2819-geometry-rh.dat");

   $zip->close();
   echo "/applications/DataExploration/curves/package.zip";

   return;  
}

// $file=tempnam("/opt/dataportal/code/StatisticsGAM2/", "txt");
//echo $file;

// for debugging save in a single file "rcode.txt" instead of a temporary file like above
$d="curves/".$user_name."_".$project_name."_curves/";
mkdir($d, 0776);
$file=$d."/rcode_include_".$project_name."_".$user_name."_".$cookie.".txt";

file_put_contents($file,$RCode);
$out = array();
exec ('/usr/bin/R --no-restore --no-save -q -f StatsScript_GAM.R --args project_name=\"'.$project_name.'\" user_name=\"'.$user_name.'\" version=\"'.$version.'\" cookie=\"'.$cookie.'\" vertexwise='.$vertexwise.' request='.$request.' 2>&1', $out);

$stop = 0;
foreach ($out as &$u) {
   if ( $u == "## model summary") {
     $stop = 1;
   }
   if ( $stop == 1 ) {
     if ( strpos($u, '>') !== 0 && strpos($u, '+ ') !== 0)
       echo $u.'<br>';
   }
}
if ( $stop == 0 ) {
   echo 'Error returned by R for project '.$project_name.'.<br>See the end of the summary statistics for the relevant error message.';
   foreach ($out as &$u) {
      echo $u.'<br>';
   }
}
file_put_contents('/tmp/bla', $out);
// if not in debug mode, remove the temporary R-command file again
// unlink($file);

?>
